travis:
  secure:
    BINSTAR_TOKEN: gUfQqz8NZpdqDVFm4/6qHUF61Vy7shZYtF8BNgkTzVFSpPAddPdIsMN/OlUl5pfySg9O39s1q7HgjZdKnjQUbfMyPjKWHlxJhvdbb5eSSVvhERMSjKBXeq11m2gliybTwTVbkc3Xo+eEY17QgVvzqGx0RxTxSptTeHTRSWCXAnaM/utxWwKz85DWd7q1GZJNd/wIelDJToDEomve1VitP7QGAFuYiah8TtNAPZJP3IXuK0OcNPF0z3pxZHveuC8lHQ3fkHjrZRJnsjwdk5iYOnx9gcPSylSwnED2Cd+ycx0cq+3ZuPoF0SZDvbTcsolavF9B9yh2qLpg9vbQVcKpeKWoVbFZMqWZtL/kq1AwPNsJ8a+KZ6lmGipPK6/yZelSJb4iRjJDOdCVv/xiMBKsj1cKOYbDBUgUmIEQdKg67Y34vIMnqdzFaEu7Fc3g7yV4sbh2ucxoaX2eOae0VBAF/V8rpBHfMccL1xhoQYEn4KYbYOMwTUj/3eTu6JT1rjJ8pOe3NUDoyrHRWKO4nT+FNQJiPNhZht281RxlnqMT9W20yAMskicoYwsyk62KysYRl4ybJkzkPhw6ByUrN3O8jKnOxEGTCWjbXdN4VYit/nzRObm7JQRzzrcLbU26/yeuVwbnM6dAFsBDysISqSa/aZ93ytpFXaV5Bm6N1VrNYj0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
