travis:
  secure:
    BINSTAR_TOKEN: FUsojC0DLC5Wu1QXKLDAn3hhNGqmZw2KE5ML9EwT9y909XjdYGexX+7T/5HDGAj8zW4hWuHGeasrJAo5+1DFtK/vyDRGtNPbOmzy67bIVU98AwEvzWHazk6oDiOWN/OQtzdmPkK1tUF9uNgy1YETo4+XH1HCc9bMJPF2YLkdGjTjQqicazjR74TdIWgGuYzaY0qQtfhhaCPNZkyQ/lvNaB8ohB6XhJXCOXz1xZt8FAP5eYHyT5HoUcT7lwN2f1DrGUnVhjgFezAS96tlgQGYHeUie55kscdNfJL/hfiVbL8eRjw4oRjjdWNJFET+sarIw/VZIAR9BvSwWozV7n9vkngHqUrYQKSf2JWg2HlP9yGlq3s0htrlc0fggOCpHmP5n2iBA5zAeme05nLOj8SveIEMOqK84cgXrBk8i87IO66ixdb/Sk9la55jmNwo5Zs3AIHXu0rznjtr/U561eGim4XmiXWwapeuO0zKCODUQ68J3/7mgNnUN1u14QDQ+xLwFfb140/boFoqUeOVNbgcNr3Gyl/2LkV9UghdGrB1or0GPjm0JIjCRMDY3cJKe/qPuNX1ZlDPCM9ko/xjmU5GxIa+xMbA2FjMn/jm8O9u5153qpxOxyR/OAwemDeb+k+Iv7UVtnFMPOkukRTGAA3UruZxBE8xX5XnRL7IZSTRhgY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
