travis:
  secure:
    BINSTAR_TOKEN: wYcYNqZwD4SXY5TF/Qd/FHF67VeI+MNKt/5xMe60bqn1dapCG8PB6MWGxMK+jwy+wqstwUN1imrdkFHY9fdU1xj4+1WPzAbwZChmUdHYNw3RP9InSLVm1nPXwe4xAdBEZv/zOFz0Aewb5+IixO7FWwpxWAt9/Cyh5i5/CME0VSGEEZwfGzyJMd8qqrZj1QGy9p8orOOoMDiuFMfelt0+RDiVwKW+Onj8fSKGOzdy9f9WxUxd6K8BSIXzWqpW0JrRa+OE2DunxGbINYAHlDr6jnNB/7qKk2Em3rr0NjAiD9MGTUK/R7HEvy/8vY9zIwouba7i124Sf1sZ82zHWbPcHIa2PiB4B5JrhUbd35dSV30oau9sI/Ql0gOK1keGCHaJtus8MRjNXLNu5/36OpbV4nBPF7Liz2TL9fHkMmHU+JuPRNfK4s7Cys4EyYP6VsfwHSKRWSypsJFaK8wHo/JwxLgDd7VHv5fh3qUjVqgmCKZZskjJ1Tn16w8VGFULA6zPAXO4CgkcONC4xOy9VmXaQ/W67HexOFhhXK2GkDaJZK+nRizrpxzn4up01PeCfopdNIJVC0EWKjxz41y+heYeOMVnH4qMNs20ysmYX2SQvDWHY3WZHXVjJVubwYvggO0u04idGxpLqr33uflkAz/BGdR4Ldo1NCDD3vQfxBvYM40=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
